// This file contains all the treatment data and their SEO-friendly details.
export const treatments = [
  {
    name: "Piles (मुळव्याध)",
    category: "Anorectal",
    slug: "piles-treatment",
    shortDescription: "Advanced and painless treatment for piles (Hemorrhoids).",
    description: "At Anant Clinic, Dr. Om Dwivedi offers highly advanced, minimally invasive Ayurvedic and integrated treatments for Piles (Hemorrhoids). We focus on providing quick relief from pain, bleeding, and discomfort with a minimal recurrence rate.",
    symptoms: ["Bleeding during bowel movements", "Itching or irritation in your anal region", "Pain or discomfort", "Swelling around your anus"],
    benefits: ["Painless Procedures", "No prolonged bed rest", "Permanent relief", "Holistic Ayurvedic approach"],
  },
  {
    name: "Fistula (भगंदर)",
    category: "Anorectal",
    slug: "fistula-treatment",
    shortDescription: "Specialized Ksharsutra therapy for permanent fistula cure.",
    description: "Anal fistula is a painful condition that often requires specialized care. We utilize advanced Ayurvedic techniques like Ksharsutra therapy, which has proven to be one of the most effective and permanent cures for Fistula with minimal risk of recurrence.",
    symptoms: ["Pain and swelling around the anus", "Foul-smelling drainage (pus) from an opening around the anus", "Pain with bowel movements", "Fever and chills"],
    benefits: ["High success rate", "Minimal surgical intervention", "Preservation of anal sphincter function", "Faster recovery"],
  },
  {
    name: "Fissure (फिशर)",
    category: "Anorectal",
    slug: "fissure-treatment",
    shortDescription: "Effective relief from severe anal pain and fissures.",
    description: "An anal fissure is a small tear in the thin, moist tissue (mucosa) that lines the anus. We provide soothing Ayurvedic ointments, dietary counseling, and specialized therapies to heal the tear completely without the need for complex surgery.",
    symptoms: ["Severe pain during bowel movements", "Pain after bowel movements that can last several hours", "A visible tear in the skin around the anus", "A small lump or skin tag on the skin near the anal fissure"],
    benefits: ["Non-surgical healing", "Dietary and lifestyle corrections", "Immediate pain relief", "Prevention of chronic conditions"],
  },
  {
    name: "Indigestion (अपचन होना)",
    category: "General medicine",
    slug: "indigestion-treatment",
    shortDescription: "Root-cause diagnosis and treatment for chronic indigestion.",
    description: "Chronic indigestion can disrupt your daily life. Our approach involves understanding your 'Prakriti' (body constitution) and prescribing customized Ayurvedic herbs to restore your digestive fire (Agni).",
    symptoms: ["Feeling full quickly during a meal", "Uncomfortable fullness after a meal", "Discomfort in the upper abdomen", "Nausea or bloating"],
    benefits: ["Restored gut health", "Natural herbal medicines", "Personalized diet plans", "Improved overall energy"],
  },
  {
    name: "Stomach Disorders (पेट के विकार)",
    category: "General medicine",
    slug: "stomach-disorders",
    shortDescription: "Comprehensive care for all types of stomach and gut issues.",
    description: "From IBS (Irritable Bowel Syndrome) to chronic acidity, we provide holistic treatments for a wide range of stomach disorders, ensuring long-term gut health.",
    symptoms: ["Abdominal cramps", "Excessive gas", "Changes in bowel habits", "Unexplained weight loss"],
    benefits: ["Holistic healing", "Zero side effects", "Stress management counseling", "Enhanced nutrient absorption"],
  },
  {
    name: "Hernia (हर्निया)",
    category: "Surgery",
    slug: "hernia-treatment",
    shortDescription: "Expert surgical consultation and care for Hernia.",
    description: "A hernia occurs when an internal organ pushes through a weak spot in your muscle or tissue. We provide expert surgical care and post-operative Ayurvedic healing to ensure a complete and safe recovery.",
    symptoms: ["A bulge or lump in the affected area", "Pain or discomfort, especially when coughing, bending or lifting", "A heavy or dragging sensation", "Weakness or pressure in the abdomen"],
    benefits: ["Expert surgical care", "Reduced risk of complications", "Faster post-operative healing with Ayurveda", "Comprehensive follow-up"],
  },
  {
    name: "Hydrocele (हायड्रोसील)",
    category: "Surgery",
    slug: "hydrocele-treatment",
    shortDescription: "Safe and effective surgical solutions for Hydrocele.",
    description: "Hydrocele is a type of swelling in the scrotum that occurs when fluid collects in the thin sheath surrounding a testicle. We offer safe, effective, and minimally invasive procedures to treat this condition permanently.",
    symptoms: ["Painless swelling of one or both testicles", "Heaviness in the scrotum", "Discomfort due to the size of the swelling"],
    benefits: ["Quick procedure", "Minimal downtime", "Permanent resolution", "Expert care"],
  },
  {
    name: "Appendix (अपेंडिक्स)",
    category: "Surgery",
    slug: "appendix-treatment",
    shortDescription: "Immediate and expert care for appendicitis.",
    description: "Appendicitis requires immediate medical attention. Our clinic provides prompt diagnosis and expert surgical intervention for the removal of the appendix, followed by holistic recovery plans.",
    symptoms: ["Sudden pain on the right side of the lower abdomen", "Sudden pain that begins around your navel and often shifts to your lower right abdomen", "Nausea and vomiting", "Loss of appetite"],
    benefits: ["Prompt diagnosis", "Safe surgical removal", "Infection control", "Speedy recovery protocols"],
  },
  {
    name: "Jaundice (पिलीया)",
    category: "General medicine",
    slug: "jaundice-treatment",
    shortDescription: "Ayurvedic liver detoxification and Jaundice treatment.",
    description: "Jaundice is a sign of underlying liver issues. We use powerful Ayurvedic hepatoprotective herbs to detoxify the liver, reduce bilirubin levels, and restore normal liver function.",
    symptoms: ["Yellowing of the skin and the whites of the eyes", "Dark urine", "Pale-colored stools", "Fatigue and abdominal pain"],
    benefits: ["Complete liver detox", "Natural rejuvenation", "Prevention of further liver damage", "Dietary guidance"],
  },
  {
    name: "Tumors / Lumps (गाठ)",
    category: "Surgery",
    slug: "tumor-lump-treatment",
    shortDescription: "Accurate diagnosis and surgical removal of lumps and tumors.",
    description: "Finding a lump can be concerning. We provide accurate diagnostics to determine the nature of the lump (benign or otherwise) and offer expert surgical excision with minimal scarring.",
    symptoms: ["Visible or palpable lump under the skin", "Pain or tenderness in the area", "Changes in skin texture over the lump"],
    benefits: ["Accurate diagnostics", "Safe removal", "Minimal scarring", "Biopsy services if required"],
  },
  {
    name: "Trauma Surgery",
    category: "Surgery",
    slug: "trauma-surgery",
    shortDescription: "Emergency wound care and minor trauma surgery.",
    description: "We handle minor trauma, cuts, and injuries that require surgical suturing and care, ensuring proper healing and prevention of infections.",
    symptoms: ["Deep cuts or lacerations", "Severe bleeding from a wound", "Foreign object lodged in skin"],
    benefits: ["Immediate care", "Infection prevention", "Expert suturing", "Minimal scarring"],
  },
  {
    name: "Kidney Stone (मुतखडा)",
    category: "Surgery",
    slug: "kidney-stone-treatment",
    shortDescription: "Ayurvedic and modern treatments to dissolve or remove kidney stones.",
    description: "Kidney stones can cause excruciating pain. Depending on the size of the stone, we offer Ayurvedic medicines to dissolve and flush out the stones naturally, or surgical interventions for larger stones.",
    symptoms: ["Severe, sharp pain in the side and back, below the ribs", "Pain that radiates to the lower abdomen and groin", "Pain that comes in waves and fluctuates in intensity", "Pain or burning sensation while urinating"],
    benefits: ["Natural flushing of stones", "Pain management", "Prevention of future stone formation", "Surgical options available"],
  },
  {
    name: "Gallbladder diseases",
    category: "General medicine",
    slug: "gallbladder-diseases",
    shortDescription: "Management and treatment of gallbladder stones and inflammation.",
    description: "We provide comprehensive care for gallbladder issues, including gallstones and cholecystitis, focusing on symptom relief, dietary management, and surgical referral if necessary.",
    symptoms: ["Sudden and rapidly intensifying pain in the upper right portion of your abdomen", "Back pain between your shoulder blades", "Pain in your right shoulder", "Nausea or vomiting"],
    benefits: ["Pain relief", "Dietary management", "Prevention of complications", "Holistic care"],
  },
  {
    name: "Skin diseases (चर्मरोग)",
    category: "Dermatology",
    slug: "skin-diseases-treatment",
    shortDescription: "Permanent Ayurvedic cure for Eczema, Psoriasis, and Acne.",
    description: "Skin diseases are often reflections of internal blood impurities or gut issues. Our specialized Ayurvedic treatments purify the blood (Rakta Shodhana) to provide long-lasting and permanent healing for conditions like Eczema, Psoriasis, and Acne.",
    symptoms: ["Red, inflamed, or scaly patches of skin", "Intense itching", "Dry, cracked skin that may bleed", "Pus-filled bumps (acne)"],
    benefits: ["Root cause treatment", "Blood purification", "No steroid side-effects", "Glowing, healthy skin"],
  },
  {
    name: "Infertility treatment",
    category: "Ayurveda Special",
    slug: "infertility-treatment",
    shortDescription: "Ayurvedic solutions for male and female infertility.",
    description: "We offer traditional Ayurvedic therapies, including Panchakarma and specialized herbal formulations, to balance hormones, improve reproductive health, and treat underlying causes of infertility.",
    symptoms: ["Inability to conceive", "Irregular menstrual cycles", "Hormonal imbalances"],
    benefits: ["Natural hormonal balance", "Improved reproductive health", "Stress reduction", "Personalized therapy"],
  },
  {
    name: "Menstrual disorders",
    category: "Ayurveda Special",
    slug: "menstrual-disorders",
    shortDescription: "Natural regulation of irregular or painful periods.",
    description: "Conditions like PCOS, irregular periods, and severe menstrual cramps are treated naturally through Ayurvedic lifestyle changes and specific herbs that regulate the female reproductive system.",
    symptoms: ["Irregular or skipped periods", "Extremely painful cramps", "Heavy or prolonged bleeding", "Mood swings and fatigue"],
    benefits: ["Regulated cycles", "Pain relief", "Hormonal harmony", "Improved quality of life"],
  },
  {
    name: "Leukorrhea (सफेद पानी)",
    category: "Ayurveda Special",
    slug: "leukorrhea-treatment",
    shortDescription: "Effective treatment for abnormal white discharge.",
    description: "Leukorrhea is safely and effectively treated using Ayurvedic medicines that strengthen the reproductive tract, clear infections, and restore natural balance.",
    symptoms: ["Excessive white or yellowish vaginal discharge", "Foul smell", "Itching or irritation", "Weakness or lower back pain"],
    benefits: ["Clears infections naturally", "Strengthens immunity", "Restores normal flora", "Relieves associated back pain"],
  },
  {
    name: "Anemia (रक्त की कमी)",
    category: "General medicine",
    slug: "anemia-treatment",
    shortDescription: "Natural iron supplements and diet plans to cure Anemia.",
    description: "Anemia causes chronic fatigue and weakness. We provide easily absorbable Ayurvedic iron preparations and personalized diet plans to rapidly build healthy red blood cells.",
    symptoms: ["Fatigue and weakness", "Pale or yellowish skin", "Irregular heartbeats", "Shortness of breath"],
    benefits: ["Increased energy levels", "Better iron absorption", "Natural supplements without constipation", "Improved overall vitality"],
  },
  {
    name: "Arthritis, Gout (संधीवात)",
    category: "Pain Management",
    slug: "arthritis-gout-treatment",
    shortDescription: "Ayurvedic pain management and joint lubrication for Arthritis.",
    description: "We treat Arthritis and Gout by reducing inflammation, clearing accumulated toxins (Ama) from the joints, and prescribing therapies like Janu Basti to lubricate and strengthen the joints.",
    symptoms: ["Joint pain and stiffness", "Swelling and redness around joints", "Decreased range of motion", "Intense pain attacks (in Gout)"],
    benefits: ["Reduced joint inflammation", "Improved mobility", "Prevention of joint deformity", "Long-term pain management"],
  },
  {
    name: "Joint pain (जोडो का दर्द)",
    category: "Pain Management",
    slug: "joint-pain-treatment",
    shortDescription: "Targeted therapies for all types of joint pain.",
    description: "Whether it's age-related wear and tear or injury-induced pain, our combination of internal medicines and external Ayurvedic oil therapies provides profound relief from joint pain.",
    symptoms: ["Aching or throbbing pain in joints", "Stiffness, especially in the morning", "A grating sensation with movement"],
    benefits: ["Deep tissue healing", "Lubrication of joints", "Muscle relaxation", "Enhanced flexibility"],
  },
  {
    name: "Back pain (पाठ दुखी)",
    category: "Pain Management",
    slug: "back-pain-treatment",
    shortDescription: "Relief from chronic backache, sciatica, and slipped disc issues.",
    description: "Chronic back pain and Sciatica are treated effectively using specialized Ayurvedic treatments like Kati Basti, which deeply nourishes the spinal nerves and relieves muscle spasms.",
    symptoms: ["Muscle aching", "Shooting or stabbing pain", "Pain that radiates down your leg (Sciatica)", "Pain that worsens with bending, lifting, standing or walking"],
    benefits: ["Spinal nerve nourishment", "Relief from muscle spasms", "Postural correction advice", "Avoidance of spinal surgery"],
  },
  {
    name: "Shoulder pain (कंधा दुखी)",
    category: "Pain Management",
    slug: "shoulder-pain-treatment",
    shortDescription: "Treatment for frozen shoulder and rotator cuff issues.",
    description: "We effectively treat conditions like Frozen Shoulder and muscle stiffness through targeted Ayurvedic treatments (Greeva Basti) and specific exercises to restore full range of motion.",
    symptoms: ["Pain and stiffness in the shoulder joint", "Inability to raise the arm", "Pain that worsens at night"],
    benefits: ["Restored range of motion", "Reduced stiffness", "Strengthened shoulder muscles", "Pain-free sleep"],
  },
  {
    name: "Tingling in limbs",
    category: "Pain Management",
    slug: "tingling-in-limbs",
    shortDescription: "Neurological care for numbness and tingling sensations.",
    description: "Tingling and numbness often indicate nerve compression or poor circulation. Our Ayurvedic neuro-care protocols stimulate nerve endings and improve blood circulation to the extremities.",
    symptoms: ["A 'pins and needles' sensation", "Numbness or decreased sensation", "Burning pain", "Weakness in the affected limb"],
    benefits: ["Improved nerve function", "Enhanced blood circulation", "Relief from burning sensations", "Prevention of neuropathy progression"],
  },
  {
    name: "Diabetes, BP, Obesity",
    category: "Lifestyle",
    slug: "lifestyle-diseases",
    shortDescription: "Holistic management of modern lifestyle disorders.",
    description: "Lifestyle disorders like Diabetes, Hypertension (BP), and Obesity require a multi-pronged approach. We combine Ayurvedic medicine, tailored dietary regimens, and lifestyle modifications to help you take control of your health naturally.",
    symptoms: ["Unexplained weight gain or loss", "Frequent urination and excessive thirst (Diabetes)", "Headaches and shortness of breath (BP)", "Chronic fatigue"],
    benefits: ["Natural blood sugar control", "Regulated blood pressure", "Sustainable weight loss", "Improved metabolic health"],
  }
];

export function getTreatmentBySlug(slug) {
  return treatments.find(t => t.slug === slug);
}
